/*
-- Query: select * from scoreTerms
LIMIT 0, 50000

-- Date: 2018-01-25 11:28
*/
INSERT INTO scoreTerms (name,term) VALUES ('Abdominal Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Abdominal Obesity Metabolic Syndrome','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Blood Loss Anemia','Blood loss anemia');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Congestive Heart Failure','Congestive heart failure');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Exacerbation of Chronic Obstructive Pulmonary Disease','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Lymphoblastic Leukemia (ALL)/T Lymphoblastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Acute on Chronic Systolic Congestive Heart Failure','Congestive heart failure');
INSERT INTO scoreTerms (name,term) VALUES ('Acute Renal Failure','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('Adult Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult Nasal Type Extranodal NK/T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T Lymphoblastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T-Cell Leukemia Lymphoma (ATLL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T-cell Leukemia-Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T-Cell Leukemia/Lymphoma (ATLL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Adult T-Cell Lymphoma (ATL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Advance Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced KRAS Positive Metastatic Colorectal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Malignant Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced or Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced or Metastatic ER+ Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced or Metastatic Non-small Cell Lung Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Malignant Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors or Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors or Lymphomas','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors or Non-Hodgkin''s Lymphoma (NHL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors or Non-Hodgkin''s Lymphoma (NHL)','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced Solid Tumors, Non-Small Cell Lung Carcinoma, Triple Negative Breast Cancer, Endometrial Cancer, Anaplastic Thyroid Cancer','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced/Metastatic Colorectal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Advanced/Metastatic Solid Tumors or Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Diffuse Mixed Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Diffuse Small Cleaved Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-Related Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Immunoblastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Lymphoblastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-Related Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Peripheral/Systemic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-Related Primary Effusion Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('AIDS-related Small Noncleaved Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Alcoholic Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Anaplastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Anaplastic Lymphoma Kinase-positive Non-small Cell Lung Cancer','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Angioimmunoblastic T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Anthracycline-pretreated Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Anxiety Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Anxious Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmia Atrial','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmia, Cardiac','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmias','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmias, Cardiac','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmogenic Right Ventricular Cardiomyopathy','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmogenic Right Ventricular Dysplasia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Arrhythmogenic Ventricular Cardiomyopathy','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Asthma, Chronic Obstructive Pulmonary Disease (COPD)','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Asymptomatic or Low Symptomatic Brain Metastasis in Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('B Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B Cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B Lymphoblastic Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-cell Lymphoma Recurrent','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-cell Non-Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('B-cell Non-Hodgkins Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Biliary Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Bipolar Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Bipolar Depression Depressed Phase','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Blastoid Variant Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Bradyarrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Bradycardia, Atrial Tachyarrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('BRAF V600E-mutant Metastatic Colorectal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Brain Metastases From Non-small Cell Lung Cancer (NSCLC)','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Breast Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Breast Cancer, HER2 Positive Breast Cancer, Metastatic Breast Cancer, Locally Advanced Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Broad Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Burkitt Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Burkitt''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cancer, Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Cardiac Arrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Cardiac Arrhythmias','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Cardiopulmonary Disease','Pulmonary circulation disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Castrate Resistant Prostate Cancer With Bone Metastasis','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Castration-resistant Prostate Cancer Patients With Oligometastases','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('CD19 Positive Malignant B-cell Leukemia and Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('CD19+ Diffuse Large B-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('CD30-positive Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('CD30-positive Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Central Nervous System Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cheek Line Depressions','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Chemotherapy-sensitive Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Childhood Burkitt Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Childhood Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Childhood Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Childhood Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Childhood Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Inflammatory Pulmonary Diseases','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Lymphocytic Leukemia/Small Lymphocytic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease (COPD','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease (COPD)','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease - COPD','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease COPD','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disease Severe','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Diseases','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Obstructive Pulmonary Disorder','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Renal Failure','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('Chronic Thromboembolic Pulmonary Hypertension','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Cirrhosis and Chronic Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Classical Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('cMET Dysegulation Advanced Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Coagulopathy','Coagulopathy');
INSERT INTO scoreTerms (name,term) VALUES ('Colon Cancer Liver Metastases','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Colon Cancer Liver Metastasis','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Colorectal Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Congestive Heart Failure','Congestive heart failure');
INSERT INTO scoreTerms (name,term) VALUES ('Congestive Heart Failure Due to Left Ventricular Systolic Dysfunction','Congestive heart failure');
INSERT INTO scoreTerms (name,term) VALUES ('Continued Access to Study Treatment(s), Cancers With a Mass, Bulky Tumor, Nodule, Lump, Advanced Cancer, Advanced Solid Tumors, Advanced Solid Malignancies','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('COPD (Chronic Obstructive Pulmonary Disease)','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('COPD, Chronic Obstructive Pulmonary Disease','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Core: Relapsed or Refractory Diffuse Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cutaneous T Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cutaneous T Cell Lymphoma (CTCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cutaneous T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cutaneous T-cell Lymphoma (CTCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Cystic Fibrosis Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression and Burden in Caregivers','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression Bipolar','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression in Old Age','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression Literacy','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression Not Otherwise Specified','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression Stigma','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression, Anxiety','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression, Bipolar','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression, Postpartum','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression, Unipolar','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Depression/Depressed State','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-Cell Lymphoma (DLBCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-Cell Lymphoma Activated B-Cell Type','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-Cell Lymphoma Recurrent','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-Cell Lymphoma Refractory','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-Cell Lymphoma, Not Otherwise Specified','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large B-cells Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse Large Cell Lymphoma, Adult','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Diffuse, Large B-Cell, Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Disease of Liver and Bile Duct','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Disturbance; Balance, Fluid','Fluid and electrolyte disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Drug Abuse','Drug abuse');
INSERT INTO scoreTerms (name,term) VALUES ('Drug Abuse, Intravenous','Drug abuse');
INSERT INTO scoreTerms (name,term) VALUES ('EBV Related Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('EBV Related Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('EBV Related Non-Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Elderly Metastatic Colorectal Cancer Patients','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Electrolyte Depletion','Fluid and electrolyte disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Electrolyte Disorder','Fluid and electrolyte disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Electrolyte Imbalances','Fluid and electrolyte disorders');
INSERT INTO scoreTerms (name,term) VALUES ('End Stage Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('End Stage Renal Failure on Dialysis','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('End-stage Liver Disease (ESLD)','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Enteropathy Associated T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Enteropathy-Associated T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Enteropathy-type Intestinal T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Epidermotropic T-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Epstein-Barr Virus-positive Diffuse Large B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Excluding T Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Extranodal Marginal Zone B-cell Lymphoma of Mucosa-associated Lymphoid Tissue','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Extranodal Marginal Zone Lymphoma of Mucosa-Associated Lymphoid Tissue','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Extranodal NK-T-Cell Lymphoma, Nasal Type','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Extranodal NK/T-cell Lymphoma, Nasal Type','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma (FL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma Grade IIIa','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma, Grade 1','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma, Grade 2','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphoma, Grade 3b','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Follicular T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Gastric Cancer, Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Grade 1 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Grade 2 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Grade 3 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Grade 3a Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Grade 3b Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Gray Zone Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Heart Failure, Congestive','Congestive heart failure');
INSERT INTO scoreTerms (name,term) VALUES ('Hepato-splenic T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Hepatosplenic T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('HER2 Positive Breast Cancer, Metastatic Breast Cancer, Locally Advanced Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('HER2 Positive Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('HER2 Positive Untreated Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('High Grade B-Cell Lymphoma, Not Otherwise Specified','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('High-Grade B-Cell Lymphoma With MYC and BCL2 and/or BCL6 Rearrangements','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Hodgkins Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Hypertension, Pulmonary','Pulmonary circulation disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Hypothalamic Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('IDH1 Mutated Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('In Situ Small Bowel T Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Indolent Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Indolent B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Indolent B-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Indolent Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Indolent Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Intraocular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Iron Deficiency Anemia','Deficiency anemia');
INSERT INTO scoreTerms (name,term) VALUES ('Iron-deficiency Anemia','Deficiency anemia');
INSERT INTO scoreTerms (name,term) VALUES ('Iron-refractory, Iron-deficiency Anemia (IRIDA)','Deficiency anemia');
INSERT INTO scoreTerms (name,term) VALUES ('Is Targeted Therapy Increasing Survival Inoperable Nonsmall Cell Lung Cancer With Spinal Metastasis ?','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Large B Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Leukemia-Lymphoma, Adult T-Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Liver Diseases','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Liver Metastasis Colon Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Liver, Biliary, Pancreas and Gastrointestinal Disease, Nos','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Locally Advanced and Metastatic Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Locally Advanced or Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Locally Advanced or Metastatic Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Locally Advanced Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Lung Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoblastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, B Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, B-Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, B-Cell, Marginal Zone','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Extranodal NK-T-Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Follicular','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Hodgkin','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Large B-Cell, Diffuse','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Large B-Cell, Diffuse (DLBCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Large-Cell, Anaplastic','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Malignant','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Mantle-Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Marginal Zone','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Non-Hodgkin','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Non-Hodgkin''s','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Non-hodgkins','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, Small Lymphocytic','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, T-Cell, Cutaneous','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma, T-Cell, Peripheral','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoma,Non-Hodgkin','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('LymphomaMalignant','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphomas Non-Hodgkin''s B-Cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphomatoid Papulosis','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphomatous Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Lymphoplasmacytic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Major Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Major Depression Disorder','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Major Depression Mild','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Malignant Advanced Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Malignant Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Malignant Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Malignant Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mantle Cell Lymphoma (MCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mantle Cell Lymphoma and Diffuse Large B Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mantle Cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mantle-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Marginal Zone B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Marginal Zone Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Maternal Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Maternal Obesity Complicating Childbirth','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Maternal Obesity Complicating Pregnancy','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Mature T-Cell and NK-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mediastinal (Thymic) Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Mediastinal Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Men With Mild Abdominal Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Bladder Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Brain Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Breastcancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Cancer Patients on an Anti-cancer Therapy','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Cancer to the Lung','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Cancers','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castrate Resistant Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castrate Resistant Prostate Cancer (mCRPC)','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castration Resistant Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castration Resistant Prostate Cancer (mCRPC)','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castration-Resistant Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Castration-resistant Prostate Cancer (CRPCa)','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Colon Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Colorectal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Endometrial Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Esophageal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Hormone Sensitive Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Kidney Cancers','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Liver Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Liver Cancer From Any Cancer Site','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Lung Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Nasopharyngeal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Non Small Cell Lung Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Non-small Cell Lung Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic or Advanced Non-Small Cell Lung Cancer (NSCLC)','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Ovarian Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Pancreatic Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Prostate Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Prostate Cancer, CTC','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Renal Cell Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Solid Tumor Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Squamous Neck Cancer With Occult Primary Squamous Cell Carcinoma','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Squamous Non-Small Cell Lung Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Triple Negative Breast Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Metastatic Urothelial Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Microsatellite Instability-High (MSI-H) Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Mild Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Mild to Moderate Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Moderate Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Moderate Postpartum Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Module 1: Non-GCB Diffuse Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Morbid Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Mucosa-Associated Lymphoid Tissue Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Nasal Type Extranodal NK/T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Neurodegenerative Disease','Neurodegenerative disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Neurodegenerative Diseases','Neurodegenerative disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Neurodegenerative Disorders','Neurodegenerative disorders');
INSERT INTO scoreTerms (name,term) VALUES ('NK T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('NK-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('No Previous Chemotherapy for Metastatic Esophagogastric Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Nodal Marginal Zone B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Nodal Marginal Zone Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Nodular Lymphocyte-Predominant Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non Alcoholic Fatty Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Non Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Alcoholic Fatty Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Non-alcoholic Fatty Liver Disease (NAFLD)','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin Lymphoma (NHL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin Lymphoma, B-cell','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin''s B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkin''s Lymphoma, Adult High Grade','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Hodgkins Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Non-small Cell Lung Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Small-Cell Lung Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Non-Small-Cell Lung Cancer With Bone Metastases','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Nonalcoholic Fatty Liver Disease','Liver disease');
INSERT INTO scoreTerms (name,term) VALUES ('NonHodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('NY-ESO-1 Expressing Solid Tumors in HLA-A2 Positive Patients','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity and Glomerulopathy','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity Control','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity During Pregnancy in Clinical Practice','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity Hypoventilation Syndrome','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity in Diabetes','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity in Pregnancy','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity Prevention','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Abdominal','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Adolescent','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Childhood','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Metabolically Benign','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Morbid','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Pediatric','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity, Visceral','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Obesity; Endocrine','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Opiate Induced Respiratory Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Other Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Overweight and Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Overweight or Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Overweight, Obesity and Other Hyperalimentation (E65-E68)','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Overweight, Obesity Grade I','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Pancreatic Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Paralysis','Paralysis');
INSERT INTO scoreTerms (name,term) VALUES ('Patients With Acute Exacerbation of Chronic Obstructive Pulmonary Disease','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Patients With Advanced Solid Tumor or Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Patients With Advanced Solid Tumor or Lymphoma','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Patients With Any Advanced Solid Tumors.','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Pediatric Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Pediatric Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Pediatric Patients With Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Pediatric Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Pediatric Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Perinatal Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Perioperative Coagulopathy','Coagulopathy');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral T Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral T-Cell Lymphoma (PTCL)','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral T-cell Lymphoma, NOS','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral T-Cell Lymphoma, Not Otherwise Specified','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral Vascular Disease','Peripheral vascular disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Peripheral Vascular Diseases','Peripheral vascular disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Persistent or Recurrent Cutaneous T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Plasmablastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Post-partum Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Post-stroke Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Postoperative Acute Renal Failure','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('PostPartum Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Precursor Cell Lymphoblastic Leukemia-Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Precursor T-Cell Lymphoblastic Leukemia-Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Prescription Drug Abuse','Drug abuse');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Central Nervous System Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary CNS Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Cutaneous Anaplastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Effusion Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Mediastinal (Thymic) Large B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Mediastinal Large B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Primary Pulmonary Hypertension','Pulmonary circulation disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Prostate Cancer Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Pulmonary Disease (COPD), Chronic Obstructive','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Pulmonary Disease, Chronic Obstructive','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Pulmonary Disease, Chronic Obstructive, Severe Early-Onset','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Pulmonary Embolism','Pulmonary circulation disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Pulmonary Embolism (PE)','Pulmonary circulation disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Reactive Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Rectal Cancer, Metastatic','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Burkitt Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Diffuse Mixed Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Diffuse Small Cleaved Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Grade III Lymphomatoid Granulomatosis','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Immunoblastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Lymphoblastic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Anaplastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Angioimmunoblastic T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent B-Cell Lymphoma, Unclassifiable, With Features Intermediate Between Diffuse Large B-Cell Lymphoma and Classical Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent B-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Burkitt Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Childhood Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Diffuse Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Extranodal Marginal Zone Lymphoma of Mucosa-Associated Lymphoid Tissue','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Grade 1 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Grade 2 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Grade 3 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Indolent Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Marginal Zone Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Mature T- and NK-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Mediastinal (Thymic) Large B-Cell Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Primary Cutaneous T-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Recurrent Small Lymphocytic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Anaplastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Angioimmunoblastic T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory B-Cell Lymphoma, Unclassifiable, With Features Intermediate Between Diffuse Large B-Cell Lymphoma and Classical Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Burkitt Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Diffuse Large B Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Diffuse Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Extranodal Marginal Zone Lymphoma of Mucosa-Associated Lymphoid Tissue','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Mature T-Cell and NK-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Mediastinal (Thymic) Large B-Cell Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Metastatic Colorectal Cancer','Metastatic cancer');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Small Lymphocytic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Refractory Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Relapse/Refratory Peripheral T Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed and Refractory Aggressive B- and T-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed and/or Refractory Diffuse Large B-cell Lymphoma Including With Myc Alterations','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed or Refractory Follicular Lymphoma, Relapsed or Refractory Diffuse Large B-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed or Refractory Peripheral T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed, Diffuse Large B-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed/Refractory B-cell Lymphoma, Childhood','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed/Refractory Malignant Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed/Refractory Solid Tumors/Hematological Malignancies','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Relapsed/Refractory T-cell Lymphomas','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Renal Failure','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('Renal Failure Chronic Requiring Hemodialysis','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('Renal Transplant Failure','Renal failure');
INSERT INTO scoreTerms (name,term) VALUES ('Respiratory Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Sarcopenic Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Select Advanced Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Severe Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Severe Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Severe Postpartum Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Small Intestine Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Small Lymphocytic Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Smoldering Adult T-Cell Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Pseudopapillary Tumors of the Pancreas','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor (Excluding CNS)','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor Cancers','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor Gastrointestinal','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor, Adult','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumor, Recurrent','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumors','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumors (Phase 1)','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumors and Hematologic Malignancy','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Solid Tumors Induced by Prior Radiation Exposure','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Splenic Marginal Zone Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage I Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage I Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IB Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage II Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage II Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage II Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IIA Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IIB Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Adult Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III AIDS-related Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Cutaneous T-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Grade 1 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Grade 2 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Grade 3 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III/IV Adult Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III/IV Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage III/IV Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IIIA Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IIIB Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Adult Diffuse Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Adult Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Adult Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV AIDS-related Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Cutaneous T-Cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Grade 1 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Grade 2 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Grade 3 Follicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IV Mantle Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IVA Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stage IVB Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Stress and Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Studying Maternal and Family Factors That Cause Obesity in Children','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Subcutaneous Panniculitis-Like T-Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Subjects With Abdominal Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Suspected Arrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Symptoms of Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Syndromic Obesity','Obesity');
INSERT INTO scoreTerms (name,term) VALUES ('Systemic Anaplastic Large Cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('T Cell Non-Hodgkin''s Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('T Lymphoblastic Leukemia/Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('T-cell Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('T-cell Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Tachyarrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Testicular Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('the Treatment of Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Transformed Indolent Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Transformed Lymphoma / DLBCL','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Transformed Recurrent Non-Hodgkin Lymphoma','Lymphoma');
INSERT INTO scoreTerms (name,term) VALUES ('Treatment of Chronic Obstructive Pulmonary Disease','Chronic pulmonary disease');
INSERT INTO scoreTerms (name,term) VALUES ('Treatment Resistant Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Treatment-Resistant Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Unipolar Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Unipolar Major Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Unspecified Adult Solid Tumor, Protocol Specific','Solid tumour without metastasis');
INSERT INTO scoreTerms (name,term) VALUES ('Valvular Heart Disease','Valvular disease');
INSERT INTO scoreTerms (name,term) VALUES ('Valvular Heart Disease Patients','Valvular disease');
INSERT INTO scoreTerms (name,term) VALUES ('Ventilatory Depression','Depression');
INSERT INTO scoreTerms (name,term) VALUES ('Ventricular Arrhythmia','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Ventricular Arrhythmias','Cardiac arrhythmias');
INSERT INTO scoreTerms (name,term) VALUES ('Water-Electrolyte Imbalance','Fluid and electrolyte disorders');
INSERT INTO scoreTerms (name,term) VALUES ('Weight Loss','Weight loss');
INSERT INTO scoreTerms (name,term) VALUES ('Weight Loss Programs','Weight loss');
